package com.telcel.gsa.dsaf.entity;
// Generated 12/09/2019 09:58:16 AM by Hibernate Tools 4.3.1.Final

import java.sql.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * DprBCarga generated by hbm2java
 */
@Entity
@Table(name = "BAJAS_OP_RESPALDO")
public class BajasOpRespaldo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4723751831694632853L;
	private int repaldoId;
	private String respaldoDescripcion;
	private Date respaldoFechaCarga;
	private String fechaCarga;
	private int respaldoUsuarioCreacion;
	private int respaldoEstatus;
	private int respaldoEstadoRegistro;
	private int respaldoIdSociedad;

	


	public BajasOpRespaldo() {
	}

	public BajasOpRespaldo(int repaldoId, String respaldoDescripcion, Date respaldoFechaCarga, 
			int respaldoUsuarioCreacion,
			int respaldoEstatus, int respaldoEstadoRegistro, int respaldoIdSociedad) {
		this.repaldoId = repaldoId;
		this.respaldoDescripcion = respaldoDescripcion;
		this.respaldoFechaCarga = respaldoFechaCarga;
		this.respaldoUsuarioCreacion = respaldoUsuarioCreacion;
		this.respaldoEstatus = respaldoEstatus;
		this.respaldoEstadoRegistro = respaldoEstadoRegistro;
		this.respaldoIdSociedad = respaldoIdSociedad;
	}

	public BajasOpRespaldo(int repaldoId, String respaldoDescripcion, Date respaldoFechaCarga) {

		this.repaldoId = repaldoId;
		this.respaldoDescripcion = respaldoDescripcion;
		this.respaldoFechaCarga = respaldoFechaCarga;
	}

	@Id
	@Column(name = "RESPALDO_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRepaldoId() {
		return repaldoId;
	}

	public void setRepaldoId(int repaldoId) {
		this.repaldoId = repaldoId;
	}

	
	@Column(name = "RESPALDO_DESCRIPCION", nullable = false)
	public String getRespaldoDescripcion() {
		return respaldoDescripcion;
	}

	public void setRespaldoDescripcion(String respaldoDescripcion) {
		this.respaldoDescripcion = respaldoDescripcion;
	}

	@Column(name = "RESPALDO_FECHA_CARGA", nullable = true)
	public Date getRespaldoFechaCarga() {
		return respaldoFechaCarga;
	}

	public void setRespaldoFechaCarga(Date respaldoFechaCarga) {
		this.respaldoFechaCarga = respaldoFechaCarga;
	}

	@Column(name = "RESPALDO_ESTATUS", nullable = false)
	public int getRespaldoEstatus() {
		return respaldoEstatus;
	}

	public void setRespaldoEstatus(int respaldoEstatus) {
		this.respaldoEstatus = respaldoEstatus;
	}
	
	
	@Column(name = "RESPALDO_ESTADOREGISTRO",  precision = 1, scale = 0)
	public int getRespaldoEstadoRegistro() {
		return respaldoEstadoRegistro;
	}

	public void setRespaldoEstadoRegistro(int respaldoEstadoRegistro) {
		this.respaldoEstadoRegistro = respaldoEstadoRegistro;
	}

	@Column(name = "RESPALDO_ID_SOCIEDAD", nullable = false, precision = 10, scale = 0)
	public int getRespaldoIdSociedad() {
		return respaldoIdSociedad;
	}

	public void setRespaldoIdSociedad(int respaldoIdSociedad) {
		this.respaldoIdSociedad = respaldoIdSociedad;
	}

	@Column(name = "RESPALDO_USUARIO_CREACION", nullable = false, precision = 10, scale = 0)
	public int getRespaldoUsuarioCreacion() {
		return respaldoUsuarioCreacion;
	}

	public void setRespaldoUsuarioCreacion(int respaldoUsuarioCreacion) {
		this.respaldoUsuarioCreacion = respaldoUsuarioCreacion;
	}
	@Transient
	public String getFechaCarga() {
		return fechaCarga;
	}

	public void setFechaCarga(String fechaCarga) {
		this.fechaCarga = fechaCarga;
	}
	
	
}
