package com.telcel.gsa.dsaf.entity;
// Generated 31/03/2017 01:34:30 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * BajasOpUsuario generated by hbm2java
 */
@Entity
@Table(name = "bajas_op_usuario")
public class BajasOpUsuario implements java.io.Serializable {

	 
	/**
	 * 
	 */
	private static final long serialVersionUID = 4534781980877170639L;
	private Integer id;
	private BajasOpRol bajasOpRol;
//	private String bajasCatRegion;
	private String claveEmpleado;
	private String claveUniversal;
	private String nombre;
	private String apaterno;
	private String amaterno;
	private String correo;
	private Integer usuarioCreacion;
	private Date fechaCreacion;
	private Integer usuarioModificacion;
	private Date fechaModificacion;
	private boolean estadoRegistro;
	private Integer estatusBaja;
	private String direccion;
	private String subdireccion;
	private String gerencia;
	private String departamento;
	private String puesto;
	private BajasOpUsuario usuarioSel;
	private List<BajasOpUsuario> usuarios;
	
	

	private Set<BajasOpRol> bajasOpRolsForRolUsuarioModificacion = new HashSet<BajasOpRol>(0);
	private Set<BajasOpRol> bajasOpRolsForRolUsuarioCreacion = new HashSet<BajasOpRol>(0);

	
	
	
	
	public BajasOpUsuario() {
	}

	public BajasOpUsuario(String claveEmpleado) {
		this.claveEmpleado = claveEmpleado;
	}
	
	public BajasOpUsuario(Integer id, String bajasCatRegion, String claveEmpleado,
			Integer usuarioCreacion, Date fechaCreacion, boolean estadoRegistro) {
		this.id = id;
//		this.bajasCatRegion = bajasCatRegion;
		this.claveEmpleado = claveEmpleado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.estadoRegistro = estadoRegistro;
	}

	public BajasOpUsuario(Integer id, BajasOpRol bajaOpRol, String bajasCatRegion, String claveEmpleado,
			String claveUniversal, String nombre, String apaterno, String amaterno, String correo,
			Integer usuarioCreacion, Date fechaCreacion, Integer usuarioModificacion,
			Date fechaModificacion, boolean estadoRegistro, Integer estatusBaja,
			Set<BajasOpRol> bajasOpRolsForRolUsuarioModificacion,
			Set<BajasOpRol> bajaOpRolsForRolUsuarioCreacion) {
		
		this.id = id;
		this.bajasOpRol = bajasOpRol;
//		this.bajasCatRegion =bajasCatRegion;
		this.claveEmpleado = claveEmpleado;
		this.claveUniversal = claveUniversal;
		this.nombre = nombre;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.correo = correo;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.estadoRegistro = estadoRegistro;
		this.estatusBaja = estatusBaja;
		this.bajasOpRolsForRolUsuarioModificacion = bajasOpRolsForRolUsuarioModificacion;
		this.bajasOpRolsForRolUsuarioCreacion = bajasOpRolsForRolUsuarioCreacion;
		
	}

	@Id

	@Column(name = "USUARIO_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUARIO_ROL_ID")
	public BajasOpRol getBajasOpRol() {
		return this.bajasOpRol;
	}

	public void setBajasOpRol(BajasOpRol bajasOpRol) {
		this.bajasOpRol = bajasOpRol;
	}

	
//	@Column(name = "USUARIO_REGION_ID", nullable = false)
//	public String getBajasCatRegion() {
//		return this.bajasCatRegion;
//	}
//
//	public void setBajasCatRegion(String bajasCatRegion) {
//		this.bajasCatRegion = bajasCatRegion;
//	}

	@Column(name = "USUARIO_CLAVE_EMPLEADO", nullable = false, length = 10)
	public String getClaveEmpleado() {
		return this.claveEmpleado;
	}

	public void setClaveEmpleado(String claveEmpleado) {
		this.claveEmpleado = claveEmpleado;
	}

	@Column(name = "USUARIO_CLAVE_UNIVERSAL", length = 14)
	public String getClaveUniversal() {
		return this.claveUniversal;
	}

	public void setClaveUniversal(String claveUniversal) {
		this.claveUniversal = claveUniversal;
	}

	@Column(name = "USUARIO_NOMBRE", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "USUARIO_APATERNO", length = 30)
	public String getApaterno() {
		return this.apaterno;
	}

	public void setApaterno(String apaterno) {
		this.apaterno = apaterno;
	}

	@Column(name = "USUARIO_AMATERNO", length = 30)
	public String getAmaterno() {
		return this.amaterno;
	}

	public void setAmaterno(String amaterno) {
		this.amaterno = amaterno;
	}
	
	@Column(name = "USUARIO_CORREO", length = 50)
	public String getCorreo() {
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "USUARIO_USUARIO_CREACION", nullable = false, precision = 10, scale = 0)
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USUARIO_FECHA_CREACION", nullable = false, length = 7)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "USUARIO_USUARIO_MODIFICACION", precision = 10, scale = 0)
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USUARIO_FECHA_MODIFICACION", length = 7)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "USUARIO_ESTADO_REGISTRO", nullable = false, precision = 10, scale = 0)
	public boolean getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(boolean estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	
	@Column(name = "USUARIO_ESTATUS_BAJA", precision = 22, scale = 0)
	public Integer getEstatusBaja() {
		return estatusBaja;
	}

	public void setEstatusBaja(Integer estatusBaja) {
		this.estatusBaja = estatusBaja;
	}
	
	/**
	 * @return the direccion
	 */
	@Transient
	public String getDireccion() {
		return direccion;
	}
	

	/**
	 * @param direccion the direccion to set
	 */
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	/**
	 * @return the subdireccion
	 */
	@Transient
	public String getSubdireccion() {
		return subdireccion;
	}

	/**
	 * @param subdireccion the subdireccion to set
	 */
	public void setSubdireccion(String subdireccion) {
		this.subdireccion = subdireccion;
	}

	/**
	 * @return the gerencia
	 */
	@Transient
	public String getGerencia() {
		return gerencia;
	}

	/**
	 * @param gerencia the gerencia to set
	 */
	public void setGerencia(String gerencia) {
		this.gerencia = gerencia;
	}

	/**
	 * @return the departamento
	 */
	@Transient
	public String getDepartamento() {
		return departamento;
	}

	/**
	 * @param departamento the departamento to set
	 */
	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	/**
	 * @return the puesto
	 */
	@Transient
	public String getPuesto() {
		return puesto;
	}

	/**
	 * @param puesto the puesto to set
	 */
	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	
	@Transient
	public String getNombreCompleto(){
		return this.getNombre() + " " + this.getApaterno() + " " + this.getAmaterno();
	}

	@Transient
	public BajasOpUsuario getUsuarioSel() {
		return usuarioSel;
	}

	public void setUsuarioSel(BajasOpUsuario usuarioSel) {
		this.usuarioSel = usuarioSel;
	}
	@Transient
	public List<BajasOpUsuario> getUsuarios() {
		return usuarios;
	}

	public void setUsuarios(List<BajasOpUsuario> usuarios) {
		this.usuarios = usuarios;
	}

	
	
	
}
