package com.telcel.gsa.dsaf.entity;
// Generated 31/03/2017 01:34:30 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BajasOpRol generated by hbm2java
 */
@Entity
@Table(name = "bajas_op_rol")
public class BajasOpRol implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -7085063408950893050L;
	private Integer id;
	private BajasOpUsuario usuarioModificacion;
	private BajasOpUsuario usuarioCreacion;
	private String nombre;
	private String descripcion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private boolean estadoRegistro;
	
	private Set<BajasOpUsuario> bajasOpUsuarios = new HashSet<BajasOpUsuario>(0);

	public BajasOpRol() {
	}

	public BajasOpRol(Integer id, BajasOpUsuario usuarioCreacion, String nombre, Date fechaCreacion,
			boolean estadoRegistro) {
		this.id = id;
		this.usuarioCreacion = usuarioCreacion;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.estadoRegistro = estadoRegistro;
	}

	public BajasOpRol(Integer id, BajasOpUsuario usuarioModificacion,
			BajasOpUsuario usuarioCreacion, String nombre, String descripcion,
			Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, Set<BajasOpUsuario> bajasOpUsuarios) {
		this.id = id;
		this.usuarioModificacion = usuarioModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estadoRegistro = estadoRegistro;
		this.bajasOpUsuarios = bajasOpUsuarios;
	}

	@Id
	@Column(name = "ROL_ID", unique = true, nullable = false, precision = 8, scale = 0)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_USUARIO_MODIFICACION")
	public BajasOpUsuario getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	

	public void setUsuarioModificacion(BajasOpUsuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_USUARIO_CREACION", nullable = false)
	public BajasOpUsuario getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(BajasOpUsuario usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "ROL_NOMBRE", nullable = false, length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ROL_DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ROL_FECHA_CREACION", nullable = false, length = 7)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ROL_FECHA_MODIFICACION", length = 7)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ROL_ESTADO_REGISTRO", nullable = false, precision = 1, scale = 0)
	public boolean isEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(boolean estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bajasOpRol")
	public Set<BajasOpUsuario> getBajasOpUsuarios() {
		return this.bajasOpUsuarios;
	}

	public void setBajasOpUsuarios(Set<BajasOpUsuario> bajasOpUsuarios) {
		this.bajasOpUsuarios = bajasOpUsuarios;
	}

}
