package com.telcel.gsa.dsaf.entity;
// Generated 12/02/2020 05:14:21 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * bajas_op_bitacora generated by hbm2java
 */
@Entity
@Table(name = "bajas_op_bitacora")
public class BajasBitacora implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2298259371142006742L;
	private long bitacoraId;
	private Integer rfcOpUsuarioByBitacoraUsuarioCreacion;
	private Integer rfcOpUsuarioByBitacoraUsuarioModificacion;
	private Long bitacoraLinea;
	private String bitacoraProceso;
	private Date bitacoraFechaCreacion;
	private Date bitacoraFechaModificacion;
	private boolean bitacoraEstadoRegistro;
	private String bitacoraDescripcion;

	public BajasBitacora() {
	}

	public BajasBitacora(long bitacoraId, Integer rfcOpUsuarioByBitacoraUsuarioCreacion,
			Date bitacoraFechaCreacion, boolean bitacoraEstadoRegistro) {
		this.bitacoraId = bitacoraId;
		this.rfcOpUsuarioByBitacoraUsuarioCreacion = rfcOpUsuarioByBitacoraUsuarioCreacion;
		this.bitacoraFechaCreacion = bitacoraFechaCreacion;
		this.bitacoraEstadoRegistro = bitacoraEstadoRegistro;
	}

	public BajasBitacora(long bitacoraId, Integer rfcOpUsuarioByBitacoraUsuarioCreacion,
			Integer rfcOpUsuarioByBitacoraUsuarioModificacion, Long bitacoraControlId, Long bitacoraLinea,
			String bitacoraProceso, Date bitacoraFechaCreacion, Date bitacoraFechaModificacion,
			boolean bitacoraEstadoRegistro) {
		this.bitacoraId = bitacoraId;
		this.rfcOpUsuarioByBitacoraUsuarioCreacion = rfcOpUsuarioByBitacoraUsuarioCreacion;
		this.rfcOpUsuarioByBitacoraUsuarioModificacion = rfcOpUsuarioByBitacoraUsuarioModificacion;
		this.bitacoraLinea = bitacoraLinea;
		this.bitacoraProceso = bitacoraProceso;
		this.bitacoraFechaCreacion = bitacoraFechaCreacion;
		this.bitacoraFechaModificacion = bitacoraFechaModificacion;
		this.bitacoraEstadoRegistro = bitacoraEstadoRegistro;
	}

	@Id
//    @GeneratedValue(generator = "SEQBIT")
	@Column(name = "BITACORA_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getBitacoraId() {
		return this.bitacoraId;
	}

	public void setBitacoraId(long bitacoraId) {
		this.bitacoraId = bitacoraId;
	}

	
	@Column(name = "BITACORA_USUARIO_CREACION", nullable = false)
	public Integer getRfcOpUsuarioByBitacoraUsuarioCreacion() {
		return this.rfcOpUsuarioByBitacoraUsuarioCreacion;
	}

	public void setRfcOpUsuarioByBitacoraUsuarioCreacion(Integer rfcOpUsuarioByBitacoraUsuarioCreacion) {
		this.rfcOpUsuarioByBitacoraUsuarioCreacion = rfcOpUsuarioByBitacoraUsuarioCreacion;
	}

	
	@Column(name = "BITACORA_USUARIO_MODIFICACION")
	public Integer getRfcOpUsuarioByBitacoraUsuarioModificacion() {
		return this.rfcOpUsuarioByBitacoraUsuarioModificacion;
	}

	public void setRfcOpUsuarioByBitacoraUsuarioModificacion(Integer rfcOpUsuarioByBitacoraUsuarioModificacion) {
		this.rfcOpUsuarioByBitacoraUsuarioModificacion = rfcOpUsuarioByBitacoraUsuarioModificacion;
	}

	

	@Column(name = "BITACORA_LINEA", precision = 10, scale = 0)
	public Long getBitacoraLinea() {
		return this.bitacoraLinea;
	}

	public void setBitacoraLinea(Long bitacoraLinea) {
		this.bitacoraLinea = bitacoraLinea;
	}

	@Column(name = "BITACORA_PROCESO", length = 25)
	public String getBitacoraProceso() {
		return this.bitacoraProceso;
	}

	public void setBitacoraProceso(String bitacoraProceso) {
		this.bitacoraProceso = bitacoraProceso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BITACORA_FECHA_CREACION", nullable = false, length = 7)
	public Date getBitacoraFechaCreacion() {
		return this.bitacoraFechaCreacion;
	}

	public void setBitacoraFechaCreacion(Date bitacoraFechaCreacion) {
		this.bitacoraFechaCreacion = bitacoraFechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BITACORA_FECHA_MODIFICACION", length = 7)
	public Date getBitacoraFechaModificacion() {
		return this.bitacoraFechaModificacion;
	}

	public void setBitacoraFechaModificacion(Date bitacoraFechaModificacion) {
		this.bitacoraFechaModificacion = bitacoraFechaModificacion;
	}

	@Column(name = "BITACORA_ESTADO_REGISTRO", nullable = false, precision = 1, scale = 0)
	public boolean isBitacoraEstadoRegistro() {
		return this.bitacoraEstadoRegistro;
	}

	public void setBitacoraEstadoRegistro(boolean bitacoraEstadoRegistro) {
		this.bitacoraEstadoRegistro = bitacoraEstadoRegistro;
	}
	@Column(name = "BITACORA_DESCRIPCION", length = 500)
	public String getBitacoraDescripcion() {
		return bitacoraDescripcion;
	}

	public void setBitacoraDescripcion(String bitacoraDescripcion) {
		this.bitacoraDescripcion = bitacoraDescripcion;
	}
	
	

}
